version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: checkout
      - run: npm i 
      - save_cache: 
          key: "npm-packages"
          paths: 
            - /src/node_modules
      - run: npm run lint 

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: checkout
      - run: npm i 
      - restore_cache: 
          key: "npm-packages"
      - run: npm run test 
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: checkout
      - run: npm i 
      - restore_cache: 
          key: "npm-packages"
      - run: npm run audit 

workflows:
  my_workflow:
    jobs:
      
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test

